# Numpy
---

* Numpy stands for "Numerical Python"
* It is the fundamental package for numerical calculations.
* Supports N-dimensional array objects that can be used for processing multi-dimensional data.
* Supports different datatypes.

### Using Numpy we can perform the following -:

* Mathematical & logical operation on arrays
* Fourier transformation
* Linear algebra operations
* Random number generations

## Create an array
---

* An array is an ordered collection of elements of basic datatypes of given length.
* __*Syntax :*__

```python
numpy.array(object)
```

In [1]:
import numpy as np #Importing the numpy
x = np.array([2,3,4,5])
print(x)
print(type(x)) #To see the datatype of "X"

[2 3 4 5]
<class 'numpy.ndarray'>


* Numpy can handle different categorical entries.

In [2]:
y = np.array(['2','3','n','5'])
print(y)
print(type(y))

['2' '3' 'n' '5']
<class 'numpy.ndarray'>


* All elements are coerced to the same data type

## Generate arrays using linspace()
---
`numpy.linspace()` -: Returns equally spaced numbers within a given range based on the sample number

__*Syntax :*__

```python
numpy.linspace(start, stop, num, dtype, endpoint ,retstep)
```

* start - start of interval range
* stop - end of interval range
* num - number of samples to be generated
* dtype - type of output array (By default = float type)
* endpoint - "True" to include the "stop" value as endpoint
* retstep - returns the sample, step value (By default = True)

In [9]:
#Generate an array "b" with "start = 1" and "stop = 5"

b = np.linspace(start = 1, stop = 5, num = 10, endpoint = True ,retstep = False)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Specifying `retstep = True` returns the sample as well as the step value.

In [15]:
c = np.linspace(start=1, stop=5, num=10, endpoint=True, retstep=True)
print(c)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


## Generate arrays using arange()
---

`numpy.arange()` - Returns equally spaced numbers within a given range based on the step size.

***Syntax :***

```python
numpy.arange(start, stop, step)
```
* start - start of interval range
* stop - stop of interval range
* step - step size of the interval range

In [16]:
#Generate an array with "start = 1" and "stop = 10" by specifying "step = 2"

d = np.arange(start = 1, stop = 10, step = 2)
print(d)

[1 3 5 7 9]


## Generate arrays using ones()
---

`numpy.ones()` - Returns an array with given shape and type filled with ones.

***Syntax :***

```python
numpy.ones(shape, dtype)
```

* shape - integer or, sequence of integers
* dtype - datatype (default = float type)

In [17]:
#example -:

one = np.ones((3,4)) #A matrix of 3 rows and 4 columns filled with one.
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Generate arrays using zeros()
---

`numpy.zeros()` - Returns an array with given shape and type filled with zeros.

***Syntax :***

```python
numpy.zeros(shape, dtype)
```

* shape - integer or, sequence of integers
* dtype - datatype (default = float type)

In [18]:
#example -:

zero = np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Generate arrays using random.rand()
---
`numpy.random.rand` - Returns an array of given shape filled with random values.

***Syntax :***

```python
numpy.random.rand(shape)
```

* shape - integer or, sequence of intergers

In [26]:
#Generating an one-dimesional array with random numbers

random = np.random.rand(5)
print(random)

[0.67020924 0.5723663  0.04279967 0.90709403 0.50032209]


In [24]:
#Generating a random array with 5 rows and 2 columns

random1 = np.random.rand(5,2)
print(random1)

[[0.45983074 0.36156621]
 [0.5414103  0.94879059]
 [0.38512176 0.88212573]
 [0.63933826 0.66564052]
 [0.65167438 0.43575454]]


## Generate arrays using logspace()
---

`numpy.logspace` - Returns equally spaced numbers based on log scale.

***Syntax :***

```python
numpy.logspace(start, stop, num, endpoint, base, dtype)
```

* start - Start value of the sequence
* stop - Stop value of the sequence
* num - Number of samples to be generated (Default : 50)
* endpoint - If `True` then, `stop` is the last sample
* base - Base of the logspace (Default : 10.0)
* dtype - Type of the output array

In [27]:
#Generate an array with 5 samples and base = 10.0

logs = np.logspace(start = 1, stop = 10, num = 5, base = 10.0, endpoint = True)
print(logs)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


## Advantages of Numpy
---

* Numpy supports vectorized operations
* Array operations are caried out in "C" and hence the universal functions in numpy are faster than operations carried out on python lists.

### Advantages of Numpy - Speed
---

* `%timeit` module can be used to measure the execution time for snippets of code.
* Let's compare the processing speed of the list and an array using an addition operation.

In [29]:
#Creating a list

lst = range(1000)
%timeit sum(lst)

21.3 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
#Creating a numpy array

numarr = np.array(lst)
%timeit np.sum(numarr)

6.72 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


We can clearly see that the numpy array works faster than the python list

### Advantages of Numpy - Storage Space
---

* `getsizeof()` - Retuns the size of the object in bytes.

***Syntax :***

```python
sys.getsizeof(object)
```
* `itemsize` - Returns the size of one element of numpy array

***Syntax :***

```python
numpy.ndarray.itemsize
```

* Size of the list/array can be found by multiplying the size of an individual element with the number of elements in the list/array.


In [31]:
#Let's compare the list "lst" and the array "numarr" to find the memory used by each at runtime.

import sys
sys.getsizeof(1)*len(lst)

28000

In [32]:
numarr.itemsize * numarr.size

4000

We can clearly see that the numpy array uses less bytes for storage than the python list.

## Reshaping an array
---

`reshape()` - Recasts an array in a new shape without changing its data.

In [33]:
grid = np.arange(start = 1, stop = 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Dimensions
---

`shape` - Returns the dimension of an array

***Syntax :***

```python
array_name.shape
```

In [35]:
#Create an array "a"

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

## Numpy Addition
---

* `numpy.sum()` - Returns the sum of all array elements or, sum of all array elements over a given axis

***Syntax :***

```python
numpy.sum(array, axis)
```
In the above syntax -:

* array() - Input array
* axis - axis along which the sum should be calculated

In [37]:
print(np.sum(a)) #Calculates the sum of all the elements in the arrays

print(np.sum(a, axis = 0)) #Calculates the sum of elements along the column (axis = 0)

print(np.sum(a, axis = 1)) #Calculates the sum of elements along the row (axis = 1)

45
[12 15 18]
[ 6 15 24]


`numpy.add()` - Performs the elementwise addition between two arrays

***Syntax :***

```python
numpy.add(array_1, array_2)
```

In [39]:
#Let's create 2 arrays

m = np.arange(start = 1, stop = 10).reshape(3,3)
n = np.arange(start = 11, stop = 20).reshape(3,3)

print(m)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [40]:
#Let's perform the elementwise addition

add_result = np.add(m,n)
print(add_result)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


* `numpy.multiply()` - Performs elementwise multiplication between two arrays
* `numpy.subtract()` - Perfroms elementwise subtraction between two arrays
* `numpy.divide()` - Performs elementwise division between two arrays
* `numpy.remainder()` - Retruns elementwise remainder of division between two arrays

In [41]:
#Let's perform elementwise subtraction

subtract_result = np.subtract(n,m)
print(subtract_result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [42]:
#Let's perform elementwise multiplication

mult_result = np.multiply(m,n)
print(mult_result)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [44]:
#Let's perform elementwise division

div_result = np.divide(n,m)
print(div_result)

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [45]:
#Let's extract the remainder from the division

rem_result = np.remainder(n,m)
print(rem_result)

[[0 0 1]
 [2 0 4]
 [3 2 1]]


## Accessing components of an array
---