# Matrix
----
- Matrix is nothing but the rectangular arrangement of numbers in rows and columns.
-Rows run horizontally and columns run vertically.</br>
  ***Example :***
  - This is a (3x3) matrix :
  \begin{equation*}
  A = 
  \begin{pmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33}
  \end{pmatrix}
  \end{equation*}
  - This is a (3x1) matrix :
  \begin{equation*}
  A = 
  \begin{pmatrix}
  a_{11}  \\
  a_{21}  \\
  a_{31} 
  \end{pmatrix}
  \end{equation*}
  - This is a (1x3) matrix :
  \begin{equation*}
  A = 
  \begin{pmatrix}
  a_{11} & a_{12} & a_{13}
  \end{pmatrix}
  \end{equation*}

## Creating A Matrix
---
- `numpy.matrix()` : Returns a matrix from an array type object or, string of data.
- ***Syntax :***
```python
numpy.matrix(data)
```
  ***Example :***
  </br>*Create a (3X4) Matrix:*

In [4]:
import numpy as np
a = np.matrix("1,2,3,4; 4,5,6,7; 7,8,9,10")
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


- To know the matrix dimension, we can use the `.shape` command :
- `.shape` : Returns the dimension (rows and columns) of a matrix

In [3]:
a.shape

(3, 4)

- Similarly, `.shape[0]` returns the number of rows and `.shape[1]` returns the number of columns present in the matrix respectively.

In [5]:
a.shape[0]

3

In [6]:
a.shape[1]

4

- To know the number of elements present in the matrix, we can use the `.size` function :

In [8]:
a.size

12

## Modifying The Matrix
---
We can modify the matrix using some of the available built-in functions like :
- `numpy.insert()`
- `


### Modifying The Matrix With `numpy.insert()`
---
- `numpy.insert()` : Adds values at the given position and axis of the matrix.
- ***Syntax :***
```python
numpy.insert(matrix, obj, values, axis)
```
  - `matrix` : Input matrix
  - `obj` : Index position
  - `values` : Matrix of values to be inserted
  - `axis` : Axis along which the values should be inserted.</br>

***Example :***</br>
*Adding the matrix `col_new` as a new column in matrix `a`*


In [7]:
col_new = np.matrix("2,3,4")
print(col_new)

[[2 3 4]]


In [6]:
a = np.insert(a,0,col_new,axis=1) #The new column will be inserted at 0th index
print(a)

[[ 2  2  1  2  3  4]
 [ 3  3  4  5  6  7]
 [ 4  4  7  8  9 10]]


*Adding the matrix `row_new` as a new row in matrix `a`*

In [13]:
row_new = np.matrix("4,5,6,7,8,9")
print(row_new)

[[4 5 6 7 8 9]]


In [14]:
a = np.insert(a,0,row_new,axis=0)
print(a)

[[ 4  5  6  7  8  9]
 [ 2  2  1  2  3  4]
 [ 3  3  4  5  6  7]
 [ 4  4  7  8  9 10]]


### Modifying The Matrix Using Index Number
---
- Elements of the matrix can be modified using the index number.

***Example :***</br>
*Modify the value of `a[1,1]` from `2` to `-3`*

In [15]:
a[1,1]=-3
print(a)

[[ 4  5  6  7  8  9]
 [ 2 -3  1  2  3  4]
 [ 3  3  4  5  6  7]
 [ 4  4  7  8  9 10]]


*Extract the elements from the second row of matrix `a`*

In [16]:
print(a[1,:])

[[ 2 -3  1  2  3  4]]


*Extract the elements from the third column of matrix `a`*

In [18]:
print(a[:,2])

[[6]
 [1]
 [4]
 [7]]


## Matrix Algebra
---
We can perform various algebric opertaion between the matrices using numpy library such as :



### Matrix Addition
---

- `numpy.add()` : Performs elementwise addition between two matrices.
- ***Syntax :***
```python
numpy.add(matrix_1, matrix_2)
```

***Example :***
*Create two matrix with name `matA` and `matB` and perform elementwise addition*

In [20]:
matA = np.matrix(np.arange(0,20)).reshape(5,4)
matB = np.matrix(np.arange(20,40)).reshape(5,4)

print(matA)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [21]:
print(matB)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [22]:
mat_add = np.add(matA,matB)
print(mat_add)

[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]


### Matrix Subtraction
---

- `numpy.subtract()` : Performs elementwise subtraction between two matrices.
- ***Syntax :***
```python
numpy.subtract(matrix_1, matrix_2)
```

***Example :***
*Perform elementwise subtraction between `matA` and `matB`*

In [23]:
mat_subtract = np.subtract(matA, matB)
print(mat_subtract)

[[-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]]


### Matrix Multiplication (Regular)
---

- `numpy.dot()` : Performs regular matrix multiplication between two matrices.
- ***Syntax :***
```python
numpy.dot(matrix_1, matrix_2)
```

***Example :***
*Transpose the `matB` to create a `(4x5)` matrix with name `matC` and then, Perform regular matrix multiplicationn between `matA` and `matC`*

In [24]:
matC = np.transpose(matB)
print(matC)

[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [25]:
mat_multipl = np.dot(matA, matC)
print(mat_multipl)

[[ 134  158  182  206  230]
 [ 478  566  654  742  830]
 [ 822  974 1126 1278 1430]
 [1166 1382 1598 1814 2030]
 [1510 1790 2070 2350 2630]]


- We can also use `numpy.matmul()` or, `@` operator for the same matrix multiplication :

In [26]:
mat_multipl2 = np.matmul(matA,matC)
print(mat_multipl2)

[[ 134  158  182  206  230]
 [ 478  566  654  742  830]
 [ 822  974 1126 1278 1430]
 [1166 1382 1598 1814 2030]
 [1510 1790 2070 2350 2630]]


In [27]:
mat_multipl3 = matA @ matC
print(mat_multipl3)

[[ 134  158  182  206  230]
 [ 478  566  654  742  830]
 [ 822  974 1126 1278 1430]
 [1166 1382 1598 1814 2030]
 [1510 1790 2070 2350 2630]]


### Matrix Multiplication (Elementwise)
---

- `numpy.multiply()` : Performs elementwise matrix multiplication between two matrices.
- ***Syntax :***
```python
numpy.multiply(matrix_1, matrix_2)
```

***Example :***
*Perform elementwise matrix multiplicationn between `matA` and `matB`*

In [28]:
mat_elemult = np.multiply(matA,matB)
print(mat_elemult)

[[  0  21  44  69]
 [ 96 125 156 189]
 [224 261 300 341]
 [384 429 476 525]
 [576 629 684 741]]


### Matrix Division
---

- `numpy.divide()` : Performs elementwise matrix division between two matrices.
- ***Syntax :***
```python
numpy.divide(matrix_1, matrix_2)
```

***Example :***
*Perform elementwise matrix division between `matA` and `matB`*

In [29]:
mat_div = np.divide(matA,matB)
print(mat_div)

[[0.         0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923 0.25925926]
 [0.28571429 0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949]]


## Matrix Operations
---
Various matrix operations that can be performed in python using the numpy package are as follows :
- Determinant of a matrix
- Rank of a matrix
- Inverse of a matrix
- Solving system of equations


### Determinant Of A Matrix
---

- `numpy.linalg.det()` : Returns the determinant of a matrix
- ***Syntax:***
```python
numpy.linalg.det(matrix)
```

***Example :***</br>
*Create a square matrix first and then find its determinant*

In [30]:
x = np.matrix("4,5,16,7; 2,-3,2,3; 3,4,5,6; 4,7,8,9")
print(x)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [31]:
mat_det = np.linalg.det(x)
print(mat_det)

128.00000000000009


### Rank Of A Matrix
---
- `numpy.linalg.matrix_rank()` : Returns the rank of a matrix
- ***Syntax:***
```python
numpy.linalg.matrix_rank(matrix)
```

***Example :***</br>
*Find the rank of the previously created matrix `x`*

In [32]:
mat_rank = np.linalg.matrix_rank(x)
print(mat_rank)

4


### Inverse Of A Matrix
---
- `numpy.linalg.inv()` : Returns the inverse of a matrix
- ***Syntax:***
```python
numpy.linalg.inv(matrix)
```

***Example :***</br>
*Find the inverse of the previously created matrix `x`*

In [34]:
mat_inv = np.linalg.inv(x)
print(mat_inv)

[[ 9.37500000e-02 -4.68750000e-01  3.68750000e+00 -2.37500000e+00]
 [ 1.00929366e-16 -2.50000000e-01  5.00000000e-01 -2.50000000e-01]
 [ 9.37500000e-02  3.12500000e-02 -3.12500000e-01  1.25000000e-01]
 [-1.25000000e-01  3.75000000e-01 -1.75000000e+00  1.25000000e+00]]


### System Of Linear Equations
---

- Let's consider a system of linear equations as follows :
 \begin{equation*}
 3x + y +2z = 2 \\
 3x +2y+5z = -1 \\
 6x +7y+8z = 3
\end{equation*}

- Now, we can write the above equation in the form of  \begin{equation*}
 Ax = b :
\end{equation*}

 \begin{equation*}
  \begin{pmatrix}
  3 & 1 & 2 \\
  4 & 2 & 5 \\
  6 & 7 & 8
  \end{pmatrix} 
    \begin{pmatrix}
  x \\
  y \\
  z
  \end{pmatrix} = 
  \begin{pmatrix}
  2 \\
  -1 \\
  3
  \end{pmatrix}
  \end{equation*}

- `numpy.linalg.solve()` : Return the solution to the system `Ax = b`.
- ***Syntax :***
```python
numpy.linalg.solve(matrix_A, matrix_b)
```

***Example :***</br>
*Create 2 matrices `A` and `b` from the given system of linear equations and then find its solution :*

In [36]:
A = np.matrix("3,1,2; 3,2,5; 6,7,8")
print(A)

[[3 1 2]
 [3 2 5]
 [6 7 8]]


In [37]:
b = np.matrix("2,-1,3").transpose()
print(b)

[[ 2]
 [-1]
 [ 3]]


In [38]:
solution = np.linalg.solve(A,b)
print(solution)

[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
